### ISSUE TITLE
Uncaught Error: Parse error on line 1:...__number__ 165 166 () nil) (__number__ 1-----------------------^Expecting 'TOKEN', 'LIST_START', got 'LIST_END'

### ISSUE THREAD

**Issue by markokoleznik** [banacorn/agda-mode#11]
Hey, just giving you heads up.
I have a file foo.agda which looks like this:
module Foo where
  data bool : Set where
    false : bool
    true : bool

  f : bool → bool → bool
  f p q = p
  g : bool → bool
  g x = x

  id : bool → bool
  id y =?

note that if you put id y =?, exception is raised (during parsing I believe).

Here is also bunch of other stuff (stack trace), hope it helps.

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package, v0.2.17

### Stack Trace

Uncaught Error: Parse error on line 1:
...__number__ 165 166 () nil) (__number__ 1
-----------------------^
Expecting 'TOKEN', 'LIST_START', got 'LIST_END'

```
At /Users/markokoleznik/.atom/packages/agda-mode/node_modules/lisp-to-array/dist/lisp-to-array.js:112

Error: Parse error on line 1:
...__number__ 165 166 () nil) (__number__ 1
-----------------------^
Expecting 'TOKEN', 'LIST_START', got 'LIST_END'
  at Object.parseError (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/lisp-to-array/dist/lisp-to-array.js:112:15)
  at Object.parse (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/lisp-to-array/dist/lisp-to-array.js:177:22)
  at ParseSExpr._transform (/Users/markokoleznik/.atom/packages/agda-mode/lib/executable/stream/parse-s-expr.coffee:12:27)
  at ParseSExpr.Transform._read (_stream_transform.js:167:10)
  at ParseSExpr.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at ParseSExpr.Writable.write (_stream_writable.js:210:11)
  at Rectify.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Rectify.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Rectify.Readable.push (_stream_readable.js:109:10)
  at Rectify.Transform.push (_stream_transform.js:128:32)
  at /Users/markokoleznik/.atom/packages/agda-mode/lib/executable/stream/rectify.coffee:25:59
  at Array.forEach (native)
  at Rectify._transform (/Users/markokoleznik/.atom/packages/agda-mode/lib/executable/stream/rectify.coffee:25:40)
  at Rectify.Transform._read (_stream_transform.js:167:10)
  at Rectify.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Rectify.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
  5x -1:16.8.0 core:move-right (atom-text-editor.editor.is-focused.agda)
     -1:14.2.0 core:select-up (atom-text-editor.editor.is-focused.agda)
     -1:13.3.0 core:select-down (atom-text-editor.editor.is-focused.agda)
 10x -1:12.9.0 core:select-left (atom-text-editor.editor.is-focused.agda)
     -1:10.8.0 core:select-right (atom-text-editor.editor.is-focused.agda)
     -1:10.5.0 core:backspace (atom-text-editor.editor.is-focused.agda)
     -0:18.9.0 agda-mode:load (atom-text-editor.editor.is-focused.agda)
  4x -0:15.7.0 core:move-right (atom-text-editor.editor.is-focused.agda)
  8x -0:13.6.0 core:select-left (atom-text-editor.editor.is-focused.agda)
     -0:11.7.0 core:backspace (atom-text-editor.editor.is-focused.agda)
     -0:08.3.0 agda-mode:load (atom-text-editor.editor.is-focused.agda)
  4x -0:07.5.0 core:move-right (atom-text-editor.editor.is-focused.agda)
  9x -0:05.6.0 core:select-left (atom-text-editor.editor.is-focused.agda)
     -0:04.1.0 editor:newline (atom-text-editor.editor.is-focused.agda)
  7x -0:04.1.0 core:backspace (atom-text-editor.editor.is-focused.agda)
     -0:00.6.0 agda-mode:load (atom-text-editor.editor.is-focused.agda)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete-ruby",
      "language-haml"
    ]
  },
  "agda-mode": {
    "executablePath": "/Users/markokoleznik/Library/Haskell/bin/agda",
    "logLevel": 2
  }
}
```

### Installed Packages

```coffee
# User
agda-mode, v0.2.17

# Dev
No dev packages
```

**Comment by banacorn** [comment]
Thank you for reporting this.
Yes, this has something to do with the lispy parser.

I can't reproduce the issue, maybe we have different versions of `agda`, I'm having `v2.4.2`, which does not produce messages like `(165 166 () nil)`

Please try this: 
1. Go to the settings, disable `Direct Highlighting` to avoid the exception temporarily
2. Or upgrade to the latest version `v0.2.18`, and hopefully, the bug will be gone for good

**Comment by markokoleznik** [comment]
I have Agda `v2.4.2.2`. Anyhow, I updated agda-mode to version `v0.2.18` and the problem is gone.
I will close this issue.
