### ISSUE TITLE
Failed to activate the agda-mode package

### ISSUE THREAD

**Issue by diakopter** [banacorn/agda-mode#12]
1. updated atom & agda-mode to latest

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package, v0.2.18
### Stack Trace

Failed to activate the agda-mode package

```
At Cannot read property 'overlayer' of undefined

TypeError: Cannot read property 'overlayer' of undefined
    at InputMethodDecorator.initialize (/Users/mwilson/.atom/packages/agda-mode/lib/input-method.coffee:236:58)
    at InputMethodDecorator.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new InputMethodDecorator (/Users/mwilson/.atom/packages/agda-mode/lib/input-method.coffee:225:57)
    at new InputMethod (/Users/mwilson/.atom/packages/agda-mode/lib/input-method.coffee:37:24)
    at new Core (/Users/mwilson/.atom/packages/agda-mode/lib/core.coffee:40:26)
    at instantiate (/Users/mwilson/.atom/packages/agda-mode/lib/agda-mode.coffee:62:27)
    at module.exports.instantiateCore (/Users/mwilson/.atom/packages/agda-mode/lib/agda-mode.coffee:69:9)
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
    at Object.module.exports.activate (/Users/mwilson/.atom/packages/agda-mode/lib/agda-mode.coffee:47:22)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:242:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ]
  },
  "agda-mode": {
    "executablePath": "/usr/local/bin/agda",
    "libraryPath": [
    ]
  }
}
```
### Installed Packages

``` coffee
# User
agda-mode, v0.2.18
atom-pair, v1.1.5
language-agda, v0.1.1
unity-ui, v2.0.8
vim-mode, v0.46.0

# Dev
No dev packages
```

**Comment by banacorn** [comment]
Thanks for reporting this, seems like they rely on some APIs that are going away when 1.0 ships.

**Comment by banacorn** [comment]
`v0.2.20`

**Comment by markokoleznik** [comment]
Is it just me, or anyone else has reported this issue?
I've just updated Atom and agda-mode package.

Issue dump, I hope it helps.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package, v0.4.1


### Stack Trace

Failed to activate the agda-mode package

```
At Cannot read property 'get' of undefined

TypeError: Cannot read property 'get' of undefined
  at Directive._checkStatement (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directive.js:218:41)
  at Directive._bind (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directive.js:98:11)
  at linkAndCapture (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/compiler/compile.js:92:13)
  at compositeLinkFn (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/compiler/compile.js:70:16)
  at VueComponent.exports._compile (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/instance/lifecycle.js:51:7)
  at VueComponent.exports.$mount (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/api/lifecycle.js:25:8)
  at VueComponent.exports._init (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/instance/init.js:112:10)
  at VueComponent.Vue (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/vue.js:19:8)
  at new VueComponent (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/api/global.js:53:11)
  at Directive.module.exports.build (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directives/internal/component.js:209:19)
  at Directive.module.exports.mountComponent (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directives/internal/component.js:133:29)
  at /Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directives/internal/component.js:98:14
  at /Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directives/internal/component.js:113:7
  at cb (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/util/lang.js:362:17)
  at Panel.exports._resolveComponent (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/instance/misc.js:91:5)
  at Directive.module.exports.resolveComponent (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directives/internal/component.js:115:13)
  at Directive.module.exports.setComponent (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directives/internal/component.js:97:12)
  at Directive.module.exports.bind (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directives/internal/component.js:54:14)
  at Directive._bind (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/directive.js:90:10)
  at linkAndCapture (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/compiler/compile.js:92:13)
  at compositeLinkFn (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/compiler/compile.js:70:16)
  at Panel.exports._compile (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/instance/lifecycle.js:52:36)
  at Panel.exports.$mount (/Users/markokoleznik/.atom/packages/agda-mode/node_modules/vue/src/api/lifecycle.js:25:8)
  at new Core (/Users/markokoleznik/.atom/packages/agda-mode/lib/core.coffee:53:16)
  at Object.module.exports.instantiateCore (/Users/markokoleznik/.atom/packages/agda-mode/lib/agda-mode.coffee:70:27)
  at /Users/markokoleznik/.atom/packages/agda-mode/lib/agda-mode.coffee:45:14
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:276:9)
  at Object.module.exports.activate (/Users/markokoleznik/.atom/packages/agda-mode/lib/agda-mode.coffee:42:24)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:00.8.0 agda-mode:load (atom-text-editor.editor.is-focused.agda)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete-ruby"
    ]
  },
  "agda-mode": {
    "executablePath": "/Users/markokoleznik/Library/Haskell/bin/agda",
    "libraryPath": [
      "/Users/markokoleznik/Documents/agda_src"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.8
agda-mode, v0.4.1
atom-autocomplete-php, v0.18.1
codeigniter, v0.2.0
color-picker, v2.0.13
language-agda, v0.2.2
language-haml, v0.23.4
minimap, v4.15.0
remote-edit, v1.8.21

# Dev
No dev packages
```

**Comment by banacorn** [comment]
Thanks for reporting this, I will try to reproduce this on other machines.

**Comment by markokoleznik** [comment]
If anything helps, I've tried disabling all packages but agda-mode and agda-language, still the same error.

**Comment by banacorn** [comment]
This is a huge block, caused by a dependency with some backwards incompatible API changes.
Sadly I have a paper submission due coming ... I'll fix this as soon as possible

**Comment by markokoleznik** [comment]
I understand :) Good luck!

**Comment by banacorn** [comment]
v0.4.2

**Comment by markokoleznik** [comment]
Aaaam, it still throws and error...? 

`Cannot find module 'vue'`

**Comment by banacorn** [comment]
:D

**Comment by psygnisfive** [comment]
I'm getting a new version of this issue: when I try to load a file

```
Cannot read property 'charCodeAt' of undefined
Hide Stack Trace
TypeError: Cannot read property 'charCodeAt' of undefined
    at Object.f [as filepath] (/Users/beka/.atom/packages/agda-mode/lib/js/bundled.js:1:14620)
    at y (/Users/beka/.atom/packages/agda-mode/lib/js/bundled.js:6:9112)
    at /Users/beka/.atom/packages/agda-mode/lib/js/bundled.js:6:10310
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:428255)
    at Object.t.activate (/Users/beka/.atom/packages/agda-mode/lib/js/bundled.js:6:10240)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3081678)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172021)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173462)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349753)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212648)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208782)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285300)
```

**Comment by banacorn** [comment]
@psygnisfive sorry about that, I think I've identified the problem, a patch should be coming soon.
