### ISSUE TITLE
Holes Having Multiple Lines

### ISSUE THREAD

**Issue by scmu** [banacorn/agda-mode#18]
With this file

```
module AtomTst where

f : {A : Set} → A → A
f = {!
	!}
```

Atom signals an "Uncaught TypeError: Cannot read property '1' of null". The error is triggered by the line break in the hole. Remove the line break, and the problem goes away.

Here is the stack trace, if it helps:

```
/Users/scm/.atom/packages/agda-mode/lib/text-buffer/hole.coffee:99
Hide Stack Trace
TypeError: Cannot read property '1' of null
  at /Users/scm/.atom/packages/agda-mode/lib/text-buffer/hole.coffee:99:58
  at Array.map (native)
  at resizeHoles (/Users/scm/.atom/packages/agda-mode/lib/text-buffer/hole.coffee:93:12)
  at /Users/scm/.atom/packages/agda-mode/lib/text-buffer.coffee:177:27
  at TextBuffer.protectCursor (/Users/scm/.atom/packages/agda-mode/lib/text-buffer.coffee:28:18)
  at TextBuffer.goalsAction (/Users/scm/.atom/packages/agda-mode/lib/text-buffer.coffee:172:32)
  at Executable.<anonymous> (/Users/scm/.atom/packages/agda-mode/lib/core.coffee:109:25)
  at emitOne (events.js:77:13)
  at Executable.emit (events.js:166:7)
  at ParseCommand._transform (/Users/scm/.atom/packages/agda-mode/lib/executable/stream/parse-command.coffee:28:29)
  at ParseCommand.Transform._read (_stream_transform.js:167:10)
  at ParseCommand.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at ParseCommand.Writable.write (_stream_writable.js:210:11)
  at ParseSExpr.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at ParseSExpr.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at ParseSExpr.Readable.push (_stream_readable.js:109:10)
  at ParseSExpr.Transform.push (_stream_transform.js:128:32)
  at ParseSExpr._transform (/Users/scm/.atom/packages/agda-mode/lib/executable/stream/parse-s-expr.coffee:16:10)
  at ParseSExpr.Transform._read (_stream_transform.js:167:10)
  at ParseSExpr.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at ParseSExpr.Writable.write (_stream_writable.js:210:11)
  at Rectify.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Rectify.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Rectify.Readable.push (_stream_readable.js:109:10)
  at Rectify.Transform.push (_stream_transform.js:128:32)
  at /Users/scm/.atom/packages/agda-mode/lib/executable/stream/rectify.coffee:25:59
  at Array.forEach (native)
  at Rectify._transform (/Users/scm/.atom/packages/agda-mode/lib/executable/stream/rectify.coffee:25:40)
  at Rectify.Transform._read (_stream_transform.js:167:10)
  at Rectify.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Rectify.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)
```

**Comment by banacorn** [comment]
Issue reproduced, thanks for reporting this!
