### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by banacorn** [banacorn/agda-mode#22]
How to reproduce: get a goal with a type displayed in multilines and then invoke `agda-mode:goal-type`

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package, v0.3.9

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/banacorn/.atom/packages/agda-mode/lib/view/body.coffee:8

TypeError: Cannot read property '1' of null
  at parseHeader (/Users/banacorn/.atom/packages/agda-mode/lib/view/body.coffee:8:19)
  at Array.map (native)
  at VueComponent.Vue.component.computed.raw.set (/Users/banacorn/.atom/packages/agda-mode/lib/view/body.coffee:94:48)
  at VueComponent.raw (/Users/banacorn/.atom/packages/agda-mode/node_modules/vue/src/util/lang.js:135:14)
  at Watcher.cb (/Users/banacorn/.atom/packages/agda-mode/node_modules/vue/src/directives/prop.js:26:27)
  at Watcher.p.run (/Users/banacorn/.atom/packages/agda-mode/node_modules/vue/src/watcher.js:219:12)
  at run (/Users/banacorn/.atom/packages/agda-mode/node_modules/vue/src/batcher.js:53:13)
  at Array.flush (/Users/banacorn/.atom/packages/agda-mode/node_modules/vue/src/batcher.js:34:3)
  at MutationObserver.handle (/Users/banacorn/.atom/packages/agda-mode/node_modules/vue/src/util/env.js:58:16)
  at process._tickCallback (node.js:367:9)

```

### Commands

```
     -0:04.0 agda-mode:load (atom-text-editor.editor.is-focused.agda)
     -0:00.8.0 agda-mode:goal-type-and-context[Simplified] (atom-text-editor.editor.is-focused.agda)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-typescript"
    ],
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  },
  "agda-mode": {
    "libraryPath": [
      "/Users/banacorn/agda/agda-stdlib-0.9/src"
    ],
    "improveMessage": false,
    "executablePath": "/Users/banacorn/.cabal/bin/agda"
  }
}
```

### Installed Packages

```coffee
# User
agda-mode, v0.3.9
autoclose-html, v0.18.0
chester-atom-syntax, v0.1.1
language-agda, v0.2.2
language-haskell, v1.3.1
language-rust, v0.4.4
language-vue-component, v0.2.0
minimap, v4.12.3

# Dev
agda-mode, v0.3.9
language-agda, v0.2.2
```

**Comment by banacorn** [comment]
`v0.3.11`
