### ISSUE TITLE
Uncaught No candidate connections error: No candidate connections available

### ISSUE THREAD

**Issue by equivalence1** [banacorn/agda-mode#52]
[Enter steps to reproduce:]

1. open any `.agda` file
2. try to do any action (like load `C-c C-l`)

**Atom**: 1.23.0-dev-eb0da16 x64
**Electron**: 1.6.14
**OS**: Ubuntu 16.04.3
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package 0.7.3

### Stack Trace

Uncaught No candidate connections error: No candidate connections available

```
At /home/equi/.atom/packages/agda-mode/lib/connector.js:156

No candidate connections error: No candidate connections available
    at getExistingConnectionInfo (/packages/agda-mode/lib/connector.js:156:19)
    at Connector.connect (/packages/agda-mode/lib/connector.js:74:20)
    at Commander.dispatch (/packages/agda-mode/lib/commander.js:39:48)
    at HTMLElement.subscriptions.add.atom.commands.add (/packages/agda-mode/lib/agda-mode.js:106:32)
    at CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/local/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/local/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:28.6.0 editor:select-to-beginning-of-word (input.hidden-input)
  3x -3:24.1.0 core:backspace (input.hidden-input)
     -0:14.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:06.0 agda-mode:load (input.hidden-input)
```

### Non-Core Packages

```
agda-mode 0.7.3 
language-agda 0.2.5 
```

**Comment by banacorn** [comment]
Issue reproduced by removing all existing connections.
This is caused by improper error handling.
Thanks for reporting this, a patch is on the way!

**Comment by equivalence1** [comment]
@banacorn 
I've upgraded to 0.7.5 -- everything works just fine. Thanks a lot for such a quick fix!
