### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activate' of undefined

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/agda-mode#57]
I just opened the menu "Agda Mode" and then tried the option "Query Unicode ..."
This is what I got.

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package 0.7.11

### Stack Trace

Uncaught TypeError: Cannot read property 'activate' of undefined

```
At /Users/jonaprieto/.atom/packages/agda-mode/lib/view.js:281

TypeError: Cannot read property 'activate' of undefined
    at View.query (/packages/agda-mode/lib/view.js:281:29)
    at Commander.querySymbol (/packages/agda-mode/lib/commander.js:366:35)
    at Commander.dispatch (/packages/agda-mode/lib/commander.js:72:53)
    at HTMLElement.subscriptions.add.atom.commands.add.event (/packages/agda-mode/lib/agda-mode.js:110:36)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
 15x -1:07.9.0 find-and-replace:select-next (input.hidden-input)
     -0:15.9.0 agda-mode:query-symbol (input.hidden-input)
```

### Non-Core Packages

```
agda-mode 0.7.11 
date 2.1.0 
language-agda 0.2.5 
language-latex 1.1.1 
language-liquid 0.6.0 
latex 0.50.0 
latex-tree 0.3.0 
latextools 0.8.5 
markdown-image-insertion 0.2.1 
markdown-writer 2.7.3 
```

**Comment by banacorn** [comment]
Hmm, I can't seem to reproduce this :(
Is there a deterministic way of invoking it?

I'm working on something which includes rewriting the part that threw this nasty exception, hope that it will be gone in the next release.

**Comment by jonaprieto** [comment]
Closing thins issue, I couldn't reproduce it again with the new release.
