### ISSUE TITLE
windows unhelpful err msg: can't "connect" to agda, Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by rjstone** [banacorn/agda-mode#68]
I had this problem which I just managed to figure out the solution to.

My agda path was entered into the settings with single \'s, but apparently I needed double \\'s to escape the \'s. Maybe this is a general problem with atom paths in windows?

Anyway, I figured maybe I should submit this anyway just in case some better error handing would help avoid the confusion for people in the future. All I got was the TypeError which wasn't very useful.

```
TypeError: Cannot read property 'push' of undefined
    at pushInLast (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:248:31)
    at parse_sexp (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:263:13)
    at parseSExpression (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:281:12)
    at parseResponse (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:37:20)
    at Promise.map (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:9:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From previous event:
    at Object.parseResponses (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:9:20)
    at Rectifier.connection.stream.pipe.on (C:\Users\Robert\.atom\packages\agda-mode\lib\connection.js:29:30)
    at emitOne (events.js:116:13)
    at Rectifier.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Rectifier.Readable.push (_stream_readable.js:208:10)
    at Rectifier.Transform.push (_stream_transform.js:147:32)
    at Rectifier._transform (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\stream\rectifier.js:18:18)
    at Rectifier.Transform._read (_stream_transform.js:186:10)
    at Rectifier.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Rectifier.Writable.write (_stream_writable.js:290:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at Socket.reemit (C:\Users\Robert\.atom\packages\agda-mode\node_modules\duplexer\index.js:70:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
C:\Users\Robert\.atom\packages\agda-mode\lib\connection.js:108 TypeError: Cannot read property 'push' of undefined
    at pushInLast (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:248:31)
    at parse_sexp (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:263:13)
    at parseSExpression (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:281:12)
    at parseResponse (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:37:20)
    at Promise.map (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:9:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From previous event:
    at Object.parseResponses (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\response.js:9:20)
    at Rectifier.connection.stream.pipe.on (C:\Users\Robert\.atom\packages\agda-mode\lib\connection.js:29:30)
    at emitOne (events.js:116:13)
    at Rectifier.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Rectifier.Readable.push (_stream_readable.js:208:10)
    at Rectifier.Transform.push (_stream_transform.js:147:32)
    at Rectifier._transform (C:\Users\Robert\.atom\packages\agda-mode\lib\parser\stream\rectifier.js:18:18)
    at Rectifier.Transform._read (_stream_transform.js:186:10)
    at Rectifier.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Rectifier.Writable.write (_stream_writable.js:290:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at Socket.reemit (C:\Users\Robert\.atom\packages\agda-mode\node_modules\duplexer\index.js:70:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by rjstone** [comment]
Ok well I guess I spoke too soon. Now it won't work and gives me this error no matter what I change the path to.

**Comment by banacorn** [comment]
Thanks for reporting this! 

This error happens at the very beginning of the parsing pipeline, where the Emacs Lisp strings are converted to JSON format.

I think this may have something to do with some Windows encoding related issue.
I should've done more testings on Windows!

**Comment by banacorn** [comment]
I'm closing this because I've rewritten the connecting mechanism with Reasonml/OCaml.
JS runtime errors like `Cannot read property 'push' of undefined` are gone for good.
