### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by marnen** [banacorn/agda-mode#74]
[Enter steps to reproduce:]

1. Load an Agda file.
2. Execute Compute Normal Form (^C ^N). The command works, but an error alert is also displayed.

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package 0.8.5

It may be useful to know that I'm running Agda in a Docker container.

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/marnen/.atom/packages/agda-mode/lib/js/bundled.js:1

TypeError: Cannot read property 'length' of undefined
    at /packages/agda-mode/lib/js/bundled.js:1:1796)
    at /packages/agda-mode/lib/js/bundled.js:1:2371)
    at /packages/agda-mode/lib/js/bundled.js:1:2430)
    at /packages/agda-mode/lib/js/bundled.js:25:110954)
```

### Commands

```
  4x -1:17.1.0 core:backspace (input.hidden-input)
     -1:14.9.0 agda-mode:load (input.hidden-input)
     -1:10.1.0 core:undo (input.hidden-input)
     -1:04.2.0 agda-mode:load (input.hidden-input)
     -1:03.1.0 core:undo (input.hidden-input)
  3x -1:02.3.0 core:backspace (input.hidden-input)
     -0:53.9.0 agda-mode:load (input.hidden-input)
  2x -0:49.4.0 core:undo (input.hidden-input)
     -0:46.8.0 core:save (input.hidden-input)
     -0:46.1.0 agda-mode:load (input.hidden-input)
     -0:36.2.0 agda-mode:compute-normal-form[DefaultCompute] (input.hidden-input)
     -0:31.8.0 core:confirm (input.hidden-input)
     -0:23.1.0 agda-mode:compute-normal-form[DefaultCompute] (input.hidden-input)
     -0:22.5.0 core:paste (input.hidden-input)
     -0:16.9.0 core:confirm (input.hidden-input)
     -0:05.0 agda-mode:compute-normal-form[DefaultCompute] (input.hidden-input)
```

### Non-Core Packages

```
ABC-notation 1.0.1 
agda-mode 0.8.5 
aligner 1.2.4 
aligner-css 1.2.1 
aligner-gherkin 0.0.1 
aligner-javascript 1.3.0 
andika 0.1.1 
AtLilyPond 1.2.2 
borodin 0.0.1 
atom-elixir 0.2.3 
atom-ide-ui 0.13.0 
atom-unsaved-changes 0.4.0 
busy-signal 1.4.3 
coffee-compile 0.31.0 
cucumber 0.6.0 
foldername-tabs 0.2.4 
font-viewer 0.3.1 
fonts 3.1.0 
git-control 0.9.0 
git-log 0.4.1 
git-plus 8.1.0 
git-tab-status 1.9.2 
git-tabs 0.3.0 
haskell-pointfree 0.2.0 
hey-pane 1.1.2 
ide-elixir 0.2.23 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
ide-haskell-repl 0.8.2 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
language-agda 1.0.9 
language-babel 2.85.0 
language-bbcode 0.1.1 
language-docker 1.1.8 
language-elixir 0.22.1 
language-erlang 3.2.0 
language-haml 0.31.1 
language-haskell 1.17.8 
language-javascript-better 1.7.1 
language-liquid 0.7.0 
language-lisp 0.2.0 
language-opentype 0.4.1 
language-rust 0.4.12 
language-shakespeare 0.2.2 
language-svg 0.9.2 
language-vue 0.23.1 
linter 2.2.0 
linter-docker 0.3.2 
linter-ui-default 1.7.1 
markdown-table-formatter 2.9.2 
merge-conflicts 1.4.5 
monokai 0.24.0 
package-cop 0.2.10 
package-switch 0.5.0 
pdf-view 0.71.0 
pigments 0.40.2 
preview 0.19.0 
process-palette 0.17.0 
project-manager 3.3.6 
regex-railroad-diagram 0.19.4 
revert-buffer 0.6.0 
ruby-slim 0.2.0 
simple-align 0.2.0 
source-preview 0.5.3 
Sublime-Style-Column-Selection 1.7.5 
svg-preview 0.14.0 
tablr 1.8.3 
```

**Comment by banacorn** [comment]
Thanks for reporting this!

**Comment by marnen** [comment]
Thanks for fixing it! :)

**Comment by banacorn** [comment]
Sorry that it shouldn't take this long.
It's always a bad idea to release before a vacation 😂
