### ISSUE TITLE
Uncaught TypeError: e.trim is not a function

### ISSUE THREAD

**Issue by jaywunder** [banacorn/agda-mode#80]
[Enter steps to reproduce:]

1. Select a character
2. Run query symbol command

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package 0.8.8

### Stack Trace

Uncaught TypeError: e.trim is not a function

```
At /Users/jacob/.atom/packages/agda-mode/lib/js/bundled.js:41

TypeError: e.trim is not a function
    at Array.t.isEmpty (/packages/agda-mode/lib/js/bundled.js:57:26460)
    at /packages/agda-mode/lib/js/bundled.js:57:37086
    at /packages/agda-mode/lib/js/bundled.js:1:2425)
    at t.render (/packages/agda-mode/lib/js/bundled.js:1:13829)
    at so (/packages/agda-mode/lib/js/bundled.js:41:59757)
    at uo (/packages/agda-mode/lib/js/bundled.js:41:59552)
    at po (/packages/agda-mode/lib/js/bundled.js:41:63275)
    at Jo (/packages/agda-mode/lib/js/bundled.js:41:78873)
    at Yo (/packages/agda-mode/lib/js/bundled.js:41:79250)
    at Ra (/packages/agda-mode/lib/js/bundled.js:41:85774)
    at Na (/packages/agda-mode/lib/js/bundled.js:41:85154)
    at Sa (/packages/agda-mode/lib/js/bundled.js:41:84175)
    at ta (/packages/agda-mode/lib/js/bundled.js:41:83078)
    at Object.enqueueSetState (/packages/agda-mode/lib/js/bundled.js:41:47348)
    at u.w.setState (/packages/agda-mode/lib/js/bundled.js:33:1665)
    at u.s.onStateChange (/packages/agda-mode/lib/js/bundled.js:20:27371)
    at /packages/agda-mode/lib/js/bundled.js:20:36722)
    at Object.dispatch (/packages/agda-mode/lib/js/bundled.js:57:2403)
    at T.setPlainText (/packages/agda-mode/lib/js/bundled.js:20:83029)
    at t.default.querySymbol (/packages/agda-mode/lib/js/bundled.js:25:93708)
    at /packages/agda-mode/lib/js/bundled.js:25:88140)
    at /packages/agda-mode/lib/js/bundled.js:25:85460)
    at HTMLElement.u.add.atom.commands.add.t (/packages/agda-mode/lib/js/bundled.js:25:81852)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:677434)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:840576)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:835455)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212945)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209079)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285196)
```

### Commands

```
     -0:14 agda-mode:input-symbol (input.hidden-input)
     -0:11.7.0 core:backspace (input.hidden-input)
  5x -0:09.9.0 core:move-down (input.hidden-input)
  2x -0:09.0 core:move-right (input.hidden-input)
     -0:08.4.0 editor:select-to-end-of-line (input.hidden-input)
  7x -0:07.6.0 core:select-left (input.hidden-input)
     -0:05.8.0 command-palette:toggle (input.hidden-input)
     -0:04.0 core:confirm (input.hidden-input)
     -0:04.0 agda-mode:query-symbol (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
agda-mode 0.8.8 
atom-ide-racket 0.3.0 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-mermaid 3.3.1 
atom-ternjs 0.18.3 
uhh 0.1.0 
autocomplete-clang 0.11.5 
autocomplete-java 1.2.7 
autocomplete-python 1.11.0 
busy-signal 2.0.0 
chester-atom-syntax 0.3.2 
clipboard-plus 0.5.1 
color-picker 2.3.0 
emmet 2.4.3 
file-type-icons 1.3.4 
file-types 1.0.1 
haskell-ghc-mod 2.2.4 
ide-cpp 0.0.3 
ide-css 0.3.2 
ide-haskell 2.4.0 
ide-java 0.8.3 
ide-php 0.7.18 
ide-rust 0.19.4 
ide-typescript 0.8.0 
intentions 1.1.5 
language-agda 1.0.9 
language-haskell 1.18.0 
language-javascript-jsx 0.3.7 
language-lisp 0.2.0 
language-racket 0.4.0 
language-rust 0.4.12 
linter 2.3.0 
linter-eslint 8.5.0 
linter-javac 1.9.4 
linter-jshint 3.1.11 
linter-php 1.6.0 
linter-pycodestyle 2.1.3 
linter-rst 0.0.3 
linter-ui-default 1.7.1 
mcfunction 0.6.4 
merge-conflicts 1.4.5 
minimap 4.29.9 
multi-cursor 2.1.5 
pigments 0.40.2 
print-code 0.7.1 
pure-syntax 1.0.1 
react 0.18.0 
remote-ftp 2.2.2 
script 3.18.1 
Stylus 3.2.0 
tablr 1.8.3 
teletype 0.13.3 
```

**Comment by jaywunder** [comment]
Hey I've made a temp solution for the custom unicode input issue I created, but when I try to do query symbol I end up with this error.  It also happens on stable with the normal character inputs, do you have any ideas on why this is happening?

**Comment by banacorn** [comment]
Sorry, my bad.

It turned out that, `sequences` should be a `[String]`, but TypeScript failed to infer it, so it became "`any`".
https://github.com/banacorn/agda-mode/blob/6cd97fb174fb82f836a80ca1ad7131646a0bf173/src/commander.ts#L475
And I fed it to some function which was expecting a `String`, kaboom!

This is the reason why I'm moving from TypeScript to OCaml (Reasonml).
